# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TwitchCli < Formula
  desc "CLI for Twitch's developer offerings"
  homepage "https://github.com/twitchdev/twitch-cli"
  version "1.1.15"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/twitchdev/twitch-cli/releases/download/v1.1.15/twitch-cli_1.1.15_Darwin_arm64.tar.gz"
      sha256 "a1bdae25adb8ae83ade35ca2d01a79cfd6391a802bc9e2d43a6950cfa583cdfc"

      def install
        bin.install "twitch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twitchdev/twitch-cli/releases/download/v1.1.15/twitch-cli_1.1.15_Darwin_x86_64.tar.gz"
      sha256 "279916deb209656f3b97058c82518ae87262b054e6260cc1affdff18ab71b83f"

      def install
        bin.install "twitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twitchdev/twitch-cli/releases/download/v1.1.15/twitch-cli_1.1.15_Linux_arm64.tar.gz"
      sha256 "b2946ce46d1f6bf204cc0e66e1ff8e76341dff3498c0caec21b429f788f3bb23"

      def install
        bin.install "twitch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twitchdev/twitch-cli/releases/download/v1.1.15/twitch-cli_1.1.15_Linux_x86_64.tar.gz"
      sha256 "940e9419517071df197827fe1707b18bf23bc42f3af882ecc7e9c337eea182c7"

      def install
        bin.install "twitch"
      end
    end
  end

  test do
    system "#{bin}/twitch", "version"
  end
end
