# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TwitchCli < Formula
  desc "CLI for Twitch's developer offerings"
  homepage "https://github.com/twitchdev/twitch-cli"
  version "1.1.11"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/twitchdev/twitch-cli/releases/download/v1.1.11/twitch-cli_1.1.11_Darwin_arm64.tar.gz"
      sha256 "473079b61d44fe68f41ce47ac94e5d0ac7f837546444c809a9a9faf0dea0eb3e"

      def install
        bin.install "twitch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twitchdev/twitch-cli/releases/download/v1.1.11/twitch-cli_1.1.11_Darwin_x86_64.tar.gz"
      sha256 "717180d100a443c5abac19105bef9dc26b3b0da9649fd07bb3f35394bc907055"

      def install
        bin.install "twitch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twitchdev/twitch-cli/releases/download/v1.1.11/twitch-cli_1.1.11_Linux_arm64.tar.gz"
      sha256 "0f1e020e5d735cdae50ebe850380daff73ac7bcbbd12605db40e776d25b2d929"

      def install
        bin.install "twitch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/twitchdev/twitch-cli/releases/download/v1.1.11/twitch-cli_1.1.11_Linux_x86_64.tar.gz"
      sha256 "82f68b55e85b5c0cbf9992d42b531b0925f9cdf5433616b8388457950b83f2ff"

      def install
        bin.install "twitch"
      end
    end
  end

  test do
    system "#{bin}/twitch", "version"
  end
end
